[aws]
disabled = true

[git_branch]
format = " on ğŸ¿ [$branch]($style) "

[username]
show_always = true
style_user = "#eab2ff bold"
style_root = "#9A348E bold"
format = '[âŒˆ$userâŒ‰]($style) in '

[directory]
style = "#eab2ff bold"
format = "[âŒ$pathâŒ]($style)"
truncation_length = 2